import { Question } from './types';

export const MAP_EMBED_URL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3656.978864826197!2d-46.77259652396344!3d-23.535263960012586!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ceff8bd0490001%3A0x6646538053457007!2sR.%20Alice%20Manholer%20Piteri%2C%20122%20-%20Bela%20Vista%2C%20Osasco%20-%20SP%2C%2006018-160!5e0!3m2!1sen!2sbr!4v1705000000000!5m2!1sen!2sbr";

export const SHEETS_ENDPOINT = "REPLACE_WITH_YOUR_APPS_SCRIPT_URL";

export const QUESTIONS: Question[] = [
  { id: 1, text: "Rafael já queimou o rosto com óleo fervendo aos 10 anos, ficou um mês internado e passou por raspagem de pele.", isTruth: true },
  { id: 2, text: "Rafael já foi expulso de um reality musical por discutir com jurado ao vivo.", isTruth: false },
  { id: 3, text: "Já tocou na TV Globo e tem música que foi abertura de programa.", isTruth: true },
  { id: 4, text: "Uma gravadora internacional tentou comprar os direitos do nome “Bodão” como marca artística.", isTruth: false },
  { id: 5, text: "Já tocou para mais de 15 mil pessoas em um Réveillon em Angra dos Reis.", isTruth: true },
  { id: 6, text: "Já encerrou um show porque um papagaio subiu no palco e roubou o microfone.", isTruth: false },
  { id: 7, text: "Antes de empreender, viveu intensamente a fase artista, com palco, TV e streaming.", isTruth: true },
  { id: 8, text: "Já recusou convite para abrir show de banda internacional por “não gostar de avião”.", isTruth: false },
  { id: 9, text: "Seu hobby atual é vinhos, harmonizações e gastronomia.", isTruth: true },
  { id: 10, text: "Já produziu vinho artesanal em casa e tentou vender para restaurante francês.", isTruth: false },
  { id: 11, text: "Já trabalhou como sushiman por 3 meses em restaurante japonês.", isTruth: true },
  { id: 12, text: "Foi demitido de um sushi bar por trocar wasabi por guacamole.", isTruth: false },
  { id: 13, text: "Já caiu numa emboscada do Tinder, foi assaltado e quase morreu.", isTruth: true },
  { id: 14, text: "Conheceu o amor da vida em um grupo de WhatsApp chamado “Solteiros Premium”.", isTruth: false },
  { id: 15, text: "Já morou em república com mais de 20 pessoas.", isTruth: true },
  { id: 16, text: "Já morou em uma casa sem porta porque “era conceito minimalista”.", isTruth: false },
  { id: 17, text: "É fascinado por universo, ciência e astronomia.", isTruth: true },
  { id: 18, text: "Já tentou montar um telescópio caseiro usando lente de óculos escuros.", isTruth: false },
  { id: 19, text: "Já deu aula de forró pé de serra.", isTruth: true },
  { id: 20, text: "Já ganhou campeonato regional de dança vestindo chinelo e bermuda.", isTruth: false },
  { id: 21, text: "Já foi casado.", isTruth: true },
  { id: 22, text: "Já pediu casamento em um karaokê lotado às 3h da manhã.", isTruth: false },
  { id: 23, text: "Já subiu na parte mais alta de uma plataforma de petróleo.", isTruth: true },
  { id: 24, text: "Já caiu no mar durante esse trabalho e foi resgatado por um golfinho.", isTruth: false },
  { id: 25, text: "Já fez um aniversário convidando 30 pessoas e apareceram mais de 90.", isTruth: true },
  { id: 26, text: "Já proibiu aniversários depois de calcular o prejuízo no Excel.", isTruth: false },
  { id: 27, text: "Já dividiu quarto em república com um cara procurado pela polícia — e a polícia apareceu.", isTruth: true },
  { id: 28, text: "Já foi confundido com policial disfarçado durante essa abordagem.", isTruth: false },
  { id: 29, text: "Hoje lidera um ecossistema de marketing, automação e IA chamado R5 Hub.", isTruth: true },
  { id: 30, text: "Criou uma IA que escolhe vinho melhor que sommelier francês.", isTruth: false },
  { id: 34, text: "Já recusou proposta de emprego porque o dress code não permitia bermuda.", isTruth: false },
  { id: 35, text: "Valoriza mais quem senta à mesa do que networking de ocasião.", isTruth: true },
  { id: 36, text: "Mantém uma lista secreta chamada “pessoas que nunca mais sentam à mesa”.", isTruth: false },
  { id: 37, text: "É extremamente detalhista com estética, qualidade e identidade visual.", isTruth: true },
  { id: 38, text: "Já trocou toda a decoração de uma casa por causa da cor de uma almofada.", isTruth: false },
  { id: 39, text: "Tem sonho real de montar um estúdio musical próprio.", isTruth: true },
  { id: 40, text: "Já tentou gravar um álbum inteiro usando apenas sons de eletrodomésticos.", isTruth: false },
  { id: 41, text: "Viajar faz parte dos planos de vida, não só de férias.", isTruth: true },
  { id: 42, text: "Já perdeu voo porque estava explicando um projeto no aeroporto.", isTruth: false },
  { id: 43, text: "Criou projetos que misturam marketing, tecnologia, automação e IA.", isTruth: true },
  { id: 44, text: "Já tentou vender um projeto explicando tudo apenas com desenhos em guardanapo.", isTruth: false },
  { id: 45, text: "Não gosta de marketing vazio, hype sem entrega ou promessa milagrosa.", isTruth: true },
  { id: 46, text: "Já criou um slogan que foi vetado por ser “bom demais pra ser verdade”.", isTruth: false },
  { id: 47, text: "Já viveu fases de muito caos antes da fase mais estruturada.", isTruth: true },
  { id: 48, text: "Já acordou em uma cidade sem lembrar como chegou lá.", isTruth: false },
  { id: 49, text: "Lealdade é um valor inegociável pra ele.", isTruth: true },
  { id: 50, text: "Já terminou amizade por causa de uma discussão sobre churrasco.", isTruth: false },
  { id: 51, text: "Se preocupa muito com experiência: do evento ao detalhe.", isTruth: true },
  { id: 52, text: "Já cancelou plano inteiro porque o gelo acabou antes da bebida.", isTruth: false },
  { id: 53, text: "Gosta de fazer tudo bem feito — inclusive churrasco.", isTruth: true },
  { id: 54, text: "Já tentou fazer churrasco vegano por engano.", isTruth: false },
  { id: 55, text: "Se você foi convidado pra esse aniversário, é porque faz parte do círculo real.", isTruth: true },
  { id: 56, text: "O convite passou por uma curadoria com algoritmo de afinidade emocional.", isTruth: false }
];
